apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-nodejs-app
  template:
    metadata:
      labels:
        app: my-nodejs-app
    spec:
      containers:
        - name: my-nodejs-app
          image: jskshm2408/my-nodejs-app
          ports:
            - containerPort: 3000
          env:
            - name: DB_URL
              value: "mongodb://saksham:admin1234@mongo-service:27017"
---
apiVersion: v1
kind: Service
metadata:
  name: my-nodejs-service
spec:
  selector:
    app: my-nodejs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
